import requests

res = requests.get(
    "http://localhost:8080/search",
    params={
        "q": "Oil Tanker",
        "categories": "news",
        "time_range": "day",
        "format": "json",
    },
).json()

filtered = []
for r in res.get("results", []):
    filtered.append(r)

print(filtered)


[
    {
        "url": "https://www.cbsnews.com/live-updates/iran-war-trump-strait-of-hormuz-oil-tanker-israel/",
        "title": 'Live Updates: Iran rejects Trump\'s "false statements" on Strait of Hormuz as he says talks "going very well"',
        "content": 'As Trump again postpones his ultimatum to Iran and claims talks are "going very well," Tehran says he\'s lying and blocks 3 ...',
        "thumbnail": "https://www.bing.com//th?id=ONUT.EYkT5QKKmRKWfWMhs4j-6w&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "29 minutes ago | CBS News",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.cbsnews.com",
            "/live-updates/iran-war-trump-strait-of-hormuz-oil-tanker-israel/",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [1],
        "score": 1.0,
        "category": "news",
        "publishedDate": None,
    },
    {
        "template": "default.html",
        "title": "Mexican navy says petroleum tanker, natural seabed likely caused Gulf coast spill",
        "content": "An oil spill in the Gulf of \u200bMexico was caused by both natural causes and a petroleum tanker that \u200cauthorities are still trying to identify, Mexican officials said on Thursday.",
        "img_src": "",
        "iframe_src": "",
        "audio_src": "",
        "thumbnail": "https://www.reuters.com/resizer/v2/5OOZFTFIPVNA5PV24AXSSG2JZA.jpg?auth=1bcd23aaa265888fcaf8881be6aeaf36e3a0a7fbf82f89fc276af51f5ef68a3c&height=80",
        "publishedDate": "2026-03-26T18:54:43.034000+00:00",
        "pubdate": "2026-03-26 18:54:43+0000",
        "length": None,
        "views": "",
        "author": "",
        "metadata": None,
        "priority": "",
        "engines": ["reuters"],
        "open_group": False,
        "close_group": False,
        "positions": [1],
        "score": 1.0,
        "category": "news",
        "url": "https://www.reuters.com/business/energy/mexican-navy-says-vessel-natural-seabed-oil-leaks-caused-gulf-coast-spill-2026-03-26/",
        "engine": "reuters",
        "parsed_url": [
            "https",
            "www.reuters.com",
            "/business/energy/mexican-navy-says-vessel-natural-seabed-oil-leaks-caused-gulf-coast-spill-2026-03-26/",
            "",
            "",
            "",
        ],
    },
    {
        "url": "https://www.msn.com/en-in/news/world/10-pakistani-flagged-oil-tankers-to-us-through-hormuz-trump-reveals-irans-secret-gift-to-him/vi-AA1ZxAIX",
        "title": "'10 Pakistani-flagged oil tankers to US through Hormuz…': Trump reveals Iran's 'secret' gift to him",
        "content": "US President Donald Trump said Iran is allowing “ten boats of oil” to pass through the Strait of Hormuz as a goodwill gesture in ongoing backchannel talks, adding that the tankers appear to be operating under Pakistani flags.",
        "publishedDate": "2026-03-27T13:00:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DORMS.a306e276ba6a56ab164336d72b20350f%26pid%3DNews&sp=1774623012T41f95e224b0a30b52418155e9fdbe812b527114cc30fcc988a26dfe7662cfd3d",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-in/news/world/10-pakistani-flagged-oil-tankers-to-us-through-hormuz-trump-reveals-irans-secret-gift-to-him/vi-AA1ZxAIX",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [1],
        "score": 1.0,
        "category": "news",
        "pubdate": "2026-03-27 13:00:00",
    },
    {
        "url": "https://www.msn.com/en-in/news/world/10-pakistani-flagged-oil-tankers-to-us-through-hormuz-trump-reveals-iran-s-secret-gift-to-him/vi-AA1ZxAIX",
        "title": "10 Pakistani-flagged oil tankers to US through Hormuz: Trump reveals Iran's secret gift to him",
        "content": "US President Donald Trump said Iran is allowing “ten boats of oil” to pass through the Strait of Hormuz as a goodwill gesture ...",
        "thumbnail": "https://www.bing.com//th?id=ONUT.XTdTIeeEPm9uEoS6upZRiw&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "53 minutes ago | The Economic Times on MSN",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-in/news/world/10-pakistani-flagged-oil-tankers-to-us-through-hormuz-trump-reveals-iran-s-secret-gift-to-him/vi-AA1ZxAIX",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [2],
        "score": 0.5,
        "category": "news",
        "publishedDate": None,
    },
    {
        "template": "default.html",
        "title": "Dubai crude's premium slumps as sellers pile offers on to TotalEnergies",
        "content": "The spot premium on Dubai crude oil, which has soared since war began in \u200cIran, fell by more than half this week after sellers piled on offers, according to traders and data collated by Reuters on Friday.",
        "img_src": "",
        "iframe_src": "",
        "audio_src": "",
        "thumbnail": "https://www.reuters.com/resizer/v2/BR3R7JA2UJN3NE5R3WURYPSHL4.jpg?auth=2a5a0fa60d92ad5d7e05b2dcbeb31e240797e804d9bd55eae1dcd3f4027fa149&height=80",
        "publishedDate": "2026-03-27T03:13:17.676000+00:00",
        "pubdate": "2026-03-27 03:13:17+0000",
        "length": None,
        "views": "",
        "author": "",
        "metadata": "Business",
        "priority": "",
        "engines": ["reuters"],
        "open_group": False,
        "close_group": False,
        "positions": [2],
        "score": 0.5,
        "category": "news",
        "url": "https://www.reuters.com/business/energy/dubai-crudes-premium-slump-sellers-pile-offers-onto-totalenergies-2026-03-27/",
        "engine": "reuters",
        "parsed_url": [
            "https",
            "www.reuters.com",
            "/business/energy/dubai-crudes-premium-slump-sellers-pile-offers-onto-totalenergies-2026-03-27/",
            "",
            "",
            "",
        ],
    },
    {
        "url": "https://www.msn.com/en-in/news/world/a-russian-oil-tanker-is-about-to-reach-cuba-in-open-defiance-of-us-blockade-what-are-trumps-options/ar-AA1Zum47",
        "title": "A Russian Oil Tanker Is About To Reach Cuba In Open Defiance Of US Blockade. What Are Trump's Options?",
        "content": "A Russian-flagged oil tanker is en route to Cuba, posing a direct challenge to the US blockade on the island. For Donald Trump, the options are limited. Any move to stop the shipment carries significant legal risks and could escalate tensions on the global stage.",
        "publishedDate": "2026-03-26T22:28:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DOVFT.RYz1cOV3ZJjWHtIcLr8qui%26pid%3DNews&sp=1774623012T984efd0209279048d637af02bf82132a81ac516b886136ac1357742a04a14199",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-in/news/world/a-russian-oil-tanker-is-about-to-reach-cuba-in-open-defiance-of-us-blockade-what-are-trumps-options/ar-AA1Zum47",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [2],
        "score": 0.5,
        "category": "news",
        "pubdate": "2026-03-26 22:28:00",
    },
    {
        "url": "https://www.nbcnews.com/now/video/iran-forces-some-tankers-to-pay-millions-to-leave-strait-of-hormuz-260193349794",
        "title": "Iran forces some tankers to pay millions to leave Strait of Hormuz",
        "content": "Iran is forcing oil tankers to take a new route in the Strait of Hormuz through a narrow passage controlled by its ...",
        "thumbnail": "https://www.bing.com//th?id=ONUT.XKm7FwPfb-tfB19Q-Lrjhw&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "17 minutes ago | NBC News",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.nbcnews.com",
            "/now/video/iran-forces-some-tankers-to-pay-millions-to-leave-strait-of-hormuz-260193349794",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [3],
        "score": 0.3333333333333333,
        "category": "news",
        "publishedDate": None,
    },
    {
        "template": "default.html",
        "title": "Iran says it is receptive to any request from Spain, alluding to Hormuz transit",
        "content": "The Iranian embassy in Spain said on Thursday that \u200cIran would be receptive to any request from Madrid related to the Strait of Hormuz because Spain respects international law, in what is the first such concession offered to an EU state.",
        "img_src": "",
        "iframe_src": "",
        "audio_src": "",
        "thumbnail": "https://www.reuters.com/resizer/v2/VAQBEREPFZLY3LGPHL3GDW2GJY.jpg?auth=51c69dedeab9ecc254b46b649952dc390eb74c32fd193b5a0a42faad24667170&height=80",
        "publishedDate": "2026-03-26T16:23:44.508000+00:00",
        "pubdate": "2026-03-26 16:23:44+0000",
        "length": None,
        "views": "",
        "author": "",
        "metadata": "World",
        "priority": "",
        "engines": ["reuters"],
        "open_group": False,
        "close_group": False,
        "positions": [3],
        "score": 0.3333333333333333,
        "category": "news",
        "url": "https://www.reuters.com/world/europe/iran-says-receptive-any-request-spain-alluding-hormuz-transit-2026-03-26/",
        "engine": "reuters",
        "parsed_url": [
            "https",
            "www.reuters.com",
            "/world/europe/iran-says-receptive-any-request-spain-alluding-hormuz-transit-2026-03-26/",
            "",
            "",
            "",
        ],
    },
    {
        "url": "https://www.usnews.com/news/world/articles/2026-03-26/trump-suggests-that-iran-let-ten-oil-tankers-through-strait-of-hormuz",
        "title": "Trump Says Iran's 'Present' to US Was Allowing 10 Oil Tankers Through Hormuz",
        "content": "U.S. \u2060President Donald \u2060Trump suggested on Thursday \u200bthat Iran let ten oil \u200ctankers transit the \u200cStrait of Hormuz \u2060as \u2060a goodwill gesture in negotiations, including some \u200bPakistan-flagged vessels. Trump made the comments at a Cabinet \u200bmeeting in the White House,",
        "publishedDate": "2026-03-26T16:23:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DONUT.7S4j0UzQnkCRswrIoP9Z8w%26pid%3DNews&sp=1774623012T176603b85331cdaa9274ff24a39954eafbf0ac023726771ba5727b3d559131ae",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.usnews.com",
            "/news/world/articles/2026-03-26/trump-suggests-that-iran-let-ten-oil-tankers-through-strait-of-hormuz",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [3],
        "score": 0.3333333333333333,
        "category": "news",
        "pubdate": "2026-03-26 16:23:00",
    },
    {
        "url": "https://greekcitytimes.com/2026/03/28/greek-tanker-strait-of-hormuz-prokopiou/",
        "title": "Greek shipping defies risks in Strait of Hormuz oil transit",
        "content": "A third Greek-linked tanker has crossed the Strait of Hormuz, highlighting ongoing oil shipments through one of the world’s ...",
        "thumbnail": "https://www.bing.com//th?id=ONUT.DZVhhdck3nkjUiMwso7XPg&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "53 minutes ago | Greek City Times",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "greekcitytimes.com",
            "/2026/03/28/greek-tanker-strait-of-hormuz-prokopiou/",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [4],
        "score": 0.25,
        "category": "news",
        "publishedDate": None,
    },
    {
        "template": "default.html",
        "title": "Chinese ships halt attempt to exit Hormuz despite Iran safe passage assurances",
        "content": "Two Chinese container ships turned backed after trying to exit the Gulf via \u200bthe Strait of Hormuz on Friday, ship-tracking data showed, despite assurances from Iran that Chinese vessels could pass.",
        "img_src": "",
        "iframe_src": "",
        "audio_src": "",
        "thumbnail": "https://www.reuters.com/resizer/v2/NXDHPYR76FKLFOEPKJHUSJ77JY.jpg?auth=7f59a251a0d83616d42166280aecbf13e4abc613ba6887e3a0fc603426baeffc&height=80",
        "publishedDate": "2026-03-27T13:42:24.523000+00:00",
        "pubdate": "2026-03-27 13:42:24+0000",
        "length": None,
        "views": "",
        "author": "",
        "metadata": "World",
        "priority": "",
        "engines": ["reuters"],
        "open_group": False,
        "close_group": False,
        "positions": [4],
        "score": 0.25,
        "category": "news",
        "url": "https://www.reuters.com/world/china/chinese-ships-halt-attempt-exit-hormuz-despite-iran-safe-passage-assurances-2026-03-27/",
        "engine": "reuters",
        "parsed_url": [
            "https",
            "www.reuters.com",
            "/world/china/chinese-ships-halt-attempt-exit-hormuz-despite-iran-safe-passage-assurances-2026-03-27/",
            "",
            "",
            "",
        ],
    },
    {
        "url": "https://www.firstpost.com/world/ten-big-boats-of-oil-trump-says-iran-allowed-10-oil-tankers-through-hormuz-as-goodwill-gesture-13993590.html",
        "title": "Trump says Iran allowed 10 oil tankers through Hormuz as ‘goodwill gesture’",
        "content": "Iran allowed 10 oil tankers to pass through the strategic Strait of Hormuz as a “present” to show it was serious about negotiations to end the war, US President Donald Trump said Thursday.",
        "publishedDate": "2026-03-26T16:58:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DONUT.vLRHZLHtbUiYMw0zze7zbw%26pid%3DNews&sp=1774623012Tc92ca98ad107fb7467e05780297863af7f072207bd2211713290fb7672aba0d0",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.firstpost.com",
            "/world/ten-big-boats-of-oil-trump-says-iran-allowed-10-oil-tankers-through-hormuz-as-goodwill-gesture-13993590.html",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [4],
        "score": 0.25,
        "category": "news",
        "pubdate": "2026-03-26 16:58:00",
    },
    {
        "url": "https://www.yahoo.com/news/articles/chinese-ships-halt-attempt-exit-134335888.html",
        "title": "Chinese ships halt attempt to exit Hormuz despite Iran safe passage assurances",
        "content": "Two Chinese container ships turned backed after trying to exit the Gulf via the Strait of Hormuz on Friday, ship-tracking ...",
        "thumbnail": "https://www.bing.com//th?id=ONUT.FxdjE-Qo0hHX-gQutWYG1w&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "55 minutes ago | Yahoo",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.yahoo.com",
            "/news/articles/chinese-ships-halt-attempt-exit-134335888.html",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [5],
        "score": 0.2,
        "category": "news",
        "publishedDate": None,
    },
    {
        "url": "https://www.yahoo.com/news/videos/iran-allowing-oil-tankers-strait-221217689.html",
        "title": "Iran allowing some oil tankers through Strait of Hormuz",
        "content": "President Donald Trump announced Thursday morning that Iran is allowing some oil tankers through the Strait of Hormuz, as a sign of good faith for talks.",
        "publishedDate": "2026-03-26T22:30:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DONUT.zVugicuBhoqCnKLWWn4tvg%26pid%3DNews&sp=1774623012T0197395543b72ffef396f75af79ea32eee3b679cbdaf2517113fcc5d582ff5f6",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.yahoo.com",
            "/news/videos/iran-allowing-oil-tankers-strait-221217689.html",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [5],
        "score": 0.2,
        "category": "news",
        "pubdate": "2026-03-26 22:30:00",
    },
    {
        "url": "https://www.financialexpress.com/world-news/us-iran-israel-war-live-updates-trump-peace-talks-middle-east-oil-price/4183313/",
        "title": "US-Israel-Iran War LIVE: Differences between US-Israel on Iran war options, Vance tells Netanyahu ‘you were too optimistic in your assessments’, says report",
        "content": "The US-Israel war on Iran is close to hitting the full one month-mark as talks regarding diplomatic negotiations finally take ...",
        "thumbnail": "https://www.bing.com//th?id=ONUT.zA_MYdViSe6A96o_6tBpDg&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "21 minutes ago | The Financial Express",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.financialexpress.com",
            "/world-news/us-iran-israel-war-live-updates-trump-peace-talks-middle-east-oil-price/4183313/",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [6],
        "score": 0.16666666666666666,
        "category": "news",
        "publishedDate": None,
    },
    {
        "url": "https://www.msn.com/en-us/money/economy/oil-prices-falls-as-trump-says-iran-let-10-tankers-through-hormuz-as-a-present/ar-AA1ZvdZW",
        "title": "Oil prices falls as Trump says Iran let 10 tankers through Hormuz as a 'present'",
        "content": "Oil prices fell after Donald Trump said Iran had allowed 10 oil tankers to pass through the Strait of Hormuz.",
        "publishedDate": "2026-03-27T01:54:37",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DONUT.SAobkG0YXd6wCaYf5BmVZg%26pid%3DNews&sp=1774623012T59c42ead8cc64bca7b4d10310c6d2291105e06599e94e2b68c7f28e1ae1cfaec",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-us/money/economy/oil-prices-falls-as-trump-says-iran-let-10-tankers-through-hormuz-as-a-present/ar-AA1ZvdZW",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [6],
        "score": 0.16666666666666666,
        "category": "news",
        "pubdate": "2026-03-27 01:54:37",
    },
    {
        "url": "https://says.com/my/news/wfh-civil-servants-malaysia-pm-anwar-middle-east-crisis",
        "title": "Is WFH Back On The Table? Here’s What PM Anwar Said Exactly",
        "content": 'In his address, Anwar said the government is working on "more flexible working rules such as working from home" for civil ...',
        "thumbnail": "https://www.bing.com//th?id=ONUT.XKSC3Cii4d5g0cvj7SeCVQ&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "7 minutes ago | SAYS",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "says.com",
            "/my/news/wfh-civil-servants-malaysia-pm-anwar-middle-east-crisis",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [7],
        "score": 0.14285714285714285,
        "category": "news",
        "publishedDate": None,
    },
    {
        "url": "https://www.aol.com/articles/trump-reveals-present-iran-oil-173147608.html",
        "title": "Trump reveals ‘present’ from Iran as oil tankers move through Strait of Hormuz",
        "content": "Trump said oil tankers through the Strait of Hormuz signals real talks, and special envoy Steve Witkoff reports positive signs in U.S.-Iran backchannel negotiations.",
        "publishedDate": "2026-03-27T00:31:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DONUT.Uz8DUp5dkTZJEzTKwTgpeA%26pid%3DNews&sp=1774623012T4ba329b17d271177cb71369b142acd7af5f2282e822bcc523e7ab02b30428bba",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.aol.com",
            "/articles/trump-reveals-present-iran-oil-173147608.html",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [7],
        "score": 0.14285714285714285,
        "category": "news",
        "pubdate": "2026-03-27 00:31:00",
    },
    {
        "url": "https://www.msn.com/en-us/money/markets/iran-war-fallout-raises-odds-of-a-us-recession-economists-say/ar-AA1Zy7FH",
        "title": "Iran war fallout raises odds of a U.S. recession, economists say",
        "content": "Economists say the conflict in Iran is making a recession more likely, with higher energy prices hitting consumers and ...",
        "thumbnail": "https://www.bing.com//th?id=ORMS.0f8b2da04ec007563a2dba56d2471613&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "18 minutes ago | CBS News on MSN",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-us/money/markets/iran-war-fallout-raises-odds-of-a-us-recession-economists-say/ar-AA1Zy7FH",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [8],
        "score": 0.125,
        "category": "news",
        "publishedDate": None,
    },
    {
        "url": "https://novaramedia.com/2026/03/27/i-joined-the-nuestra-america-aid-convoy-to-show-cuba-its-not-alone/",
        "title": "I Joined the Nuestra América Aid Convoy to Show Cuba It’s Not Alone",
        "content": "Donald Trump’s oil embargo is part of a much wider assault by the US on national sovereignty around the world, writes Jeremy ...",
        "thumbnail": "https://www.bing.com//th?id=ONUT.ZC25L3SLPHo-bQjhbHqzbQ&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "38 minutes ago | Novara Media",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "novaramedia.com",
            "/2026/03/27/i-joined-the-nuestra-america-aid-convoy-to-show-cuba-its-not-alone/",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [9],
        "score": 0.1111111111111111,
        "category": "news",
        "publishedDate": None,
    },
    {
        "url": "https://www.msn.com/en-in/news/world/trump-reveals-irans-present-10-oil-tankers-allowed-transit-through-strait-of-hormuz/ar-AA1ZuJTO",
        "title": "Trump reveals Iran's 'present': 10 oil tankers allowed transit through Strait of Hormuz",
        "content": 'US President Donald Trump said that Iran allowed 10 oil tankers to pass through the Strait of Hormuz as a "present" to the United States amid ongoing negotiations between Tehran and Washington as the conflict continues in West Asia,',
        "publishedDate": "2026-03-27T02:22:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DORMS.7656213d97590c7353ab7923c6fb7a8c%26pid%3DNews&sp=1774623012Tb1e68f7e0fa3a5422f36624e080ac6cfe19190864e106618cfb059bc21db16db",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-in/news/world/trump-reveals-irans-present-10-oil-tankers-allowed-transit-through-strait-of-hormuz/ar-AA1ZuJTO",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [9],
        "score": 0.1111111111111111,
        "category": "news",
        "pubdate": "2026-03-27 02:22:00",
    },
    {
        "url": "https://www.msn.com/en-ph/news/world/iran-guards-say-strait-of-hormuz-closed-to-hostile-shipping/ar-AA1Zy7da",
        "title": "Iran Guards say Strait of Hormuz ‘closed’ to hostile shipping",
        "content": "NEW YORK — Iran's Revolutionary Guards said Friday that they had turned back three ships trying to transit the Strait of ...",
        "thumbnail": "https://www.bing.com//th?id=ORMS.0a08164822df218a8bbd89e19cd34306&pid=News&w=234&h=132&c=14&rs=2&qlt=90",
        "metadata": "57 minutes ago | The Manila Times on MSN",
        "engine": "bing news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-ph/news/world/iran-guards-say-strait-of-hormuz-closed-to-hostile-shipping/ar-AA1Zy7da",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["bing news"],
        "positions": [10],
        "score": 0.1,
        "category": "news",
        "publishedDate": None,
    },
    {
        "url": "https://indianexpress.com/article/world/donald-trump-iran-present-revealed-strait-of-hormuz-oil-tankers-west-asia-war-10603288/",
        "title": "Donald Trump reveals Iran’s mystery ‘present’: 10 oil tankers cleared to pass through Strait of Hormuz",
        "content": "Trump had earlier suggested that the goodwill gesture aided in the diplomatic efforts to end the war in West Asia.",
        "publishedDate": "2026-03-26T17:29:00",
        "thumbnail": "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.bing.com%2Fth%3Fid%3DONUT.VzhC2rhylUHtytf6-n0mvA%26pid%3DNews&sp=1774623012T47710b88d25262227365ec58c367e050064a4a6a40f895dacb82385e0c2c3030",
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "indianexpress.com",
            "/article/world/donald-trump-iran-present-revealed-strait-of-hormuz-oil-tankers-west-asia-war-10603288/",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [10],
        "score": 0.1,
        "category": "news",
        "pubdate": "2026-03-26 17:29:00",
    },
    {
        "url": "https://www.msn.com/en-us/politics/government/questions-grow-as-maritime-data-fails-to-confirm-the-ten-oil-tankers-president-trump-claims-are-a-gift-from-iran/ar-AA1ZwITT",
        "title": "Questions grow as maritime data fails to confirm the ten oil tankers President Trump claims are a gift from Iran",
        "content": "Global energy markets have been shaken by claims involving eight large oil tankers. These tankers were said to be part of a diplomatic arrangement in the Middle East. The report quickly drew global attention.",
        "publishedDate": "2026-03-27T11:04:15",
        "thumbnail": None,
        "engine": "startpage news",
        "template": "default.html",
        "parsed_url": [
            "https",
            "www.msn.com",
            "/en-us/politics/government/questions-grow-as-maritime-data-fails-to-confirm-the-ten-oil-tankers-president-trump-claims-are-a-gift-from-iran/ar-AA1ZwITT",
            "",
            "",
            "",
        ],
        "img_src": "",
        "priority": "",
        "engines": ["startpage news"],
        "positions": [8],
        "score": 0.125,
        "category": "news",
        "pubdate": "2026-03-27 11:04:15",
    },
]
